name: "Docker Check, Build, Push"
author: Grant Zukel <admin@idevops.io>
branding:
  icon: cloud
  color: gray-dark
description: Create Route 53 Record Sets
inputs:
  docker_username:
    description: Docker Username in Docker Hub
    required: true
  docker_password:
    description: Docker Password for Docker Hub Authentication (PAT)
    required: true
  docker_org:
    description: The Docker Org your repo is in.
    required: true
  docker_image:
    description: The Docker image name.
    required: true
  docker_tag:
    description: The tag of the docker file you wish to set.
    required: true
  docker_file_location:
    description: Location of the docker file you are building.
    required: true
runs:
  using: "composite"
  steps:
    - run: |
      #!/usr/bin/env bash

      function build_and_push {
        echo "Docker Wasn't Able to Pull Image With Tag. Build Tag Version and Push"
        echo "Build Dockerfile at path: ${DOCKER_FILE_LOCATION}"
        echo "Docker Image: ${DOCKER_ORG}/${DOCKER_IMAGE}:${DOCKER_TAG}"
        docker build -t ${DOCKER_ORG}/${DOCKER_IMAGE}:${DOCKER_TAG} ${DOCKER_FILE_LOCATION}
        docker push ${DOCKER_ORG}/${DOCKER_IMAGE}:${DOCKER_TAG}
      }
      docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
      docker pull ${DOCKER_ORG}/${DOCKER_IMAGE}:${DOCKER_TAG} || build_and_push
    shell: bash
