FROM bitnami/postgresql-repmgr:11.12.0-debian-10-r44
EXPOSE 5432
USER 1001
ENTRYPOINT [ "/opt/bitnami/scripts/postgresql-repmgr/entrypoint.sh" ]
CMD [ "/opt/bitnami/scripts/postgresql-repmgr/run.sh" ]