name: "Deploy Debian With Secrets"
author: Luke Baker <lbaker@idevops.io, Tanner Milton tmilton@idevops.io, Tim Carden tcarden@idevops.io>
branding:
  icon: cloud
  color: gray-dark
description: Deploying Debian with Vault Secrets
inputs:
  manifest:
    description: Manifest file location you wish to use.
    required: true
  namespace:
    description: K8S Namespace.
    required: true
  aws_access_key_id:
    description: AWS Access Key.
    required: true
  aws_secret_access_key:
    description: AWS Secret Key.
    required: true
  aws_default_region:
    description: The default region for aws cli.
    required: true
  k8s_cluster_name:
    description: Name of the AWS cluster to deploy into.
    required: true
  VAULT_TOKEN:
    description: Root Token 
    required: true
  url:
    description: Url to Vault KV Engine
    required: true
  tlsSkipVerify:
    description: Skipping Self Signed Certs
    required: true

runs:
  using: docker
  image: Dockerfile