name: "zaproxyscan"
author: Michael Cohen <mcohen@idevops.io>
branding:
  icon: cloud
  color: gray-dark
description: zaproxyscan
inputs:
  web_url:
    description: The web url you want to scan.
    required: true
  
runs:
  using: "composite"
  steps:
    - run: |
        #!/usr/bin/env bash
        docker run -t owasp/zap2docker-stable zap-full-scan.py -t ${{ inputs.web_url }}
      shell: bash