name: "Kubernetes validate deployment"
author: Evan Floyd <efloyd@idevops.io>, Stephen Card <scard@idevops.io>
branding:
  icon: cloud
  color: gray-dark
description: Kubernetes validate deployment
inputs:
  app_name:
    description: Name of the app you are deploying.
    required: true
  namespace:
    description: Kubernetes namespace you wish to use
    required: true
  aws_access_key_id:
    description: AWS Access Key.
    required: true
  aws_secret_access_key:
    description: AWS Secret Key.
    required: true
  aws_default_region:
    description: The default region for aws cli.
    required: true
  k8s_cluster_name:
    description: Name of the AWS cluster to deploy into.
    required: true

runs:
  using: "composite"
  steps:
  - run: |
      #!/usr/bin/env bash
      curl -sSLO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      curl -sSo aws-iam-authenticator https://s3.us-west-2.amazonaws.com/amazon-eks/1.21.2/2021-07-05/bin/darwin/amd64/aws-iam-authenticator
      pip install awscli
      export AWS_ACCESS_KEY_ID=$(echo ${{ inputs.AWS_ACCESS_KEY_ID }})
      export AWS_SECRET_ACCESS_KEY=$(echo ${{ inputs.AWS_SECRET_ACCESS_KEY }})
      export AWS_DEFAULT_REGION=$(echo ${{ inputs.AWS_DEFAULT_REGION }})
      aws eks update-kubeconfig --name ${{ inputs.k8s_cluster_name }} --region ${{ inputs.AWS_DEFAULT_REGION }}
      kubectl rollout status deployment/${{ inputs.APP_NAME }} --namespace ${{ inputs.NAMESPACE }}
    shell: bash