name: "Base 64 Encode"
author: Evan Floyd <efloyd@idevops.io>
branding:
  icon: cloud
  color: gray-dark
description: Base 64 Encode
inputs:
  encode_file:
    description: File you wish to base64 encode.
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        #!/usr/bin/env bash
        echo -n "${{ inputs.encode_file }}" | base64 
      shell: bash