name: "Use AWS CLI to pull K8S Kubeconfig"
author: Evan Floyd <efloyd@idevops.io>
branding:
  icon: cloud
  color: gray-dark
description: Use AWS CLI to pull K8S Kubeconfig
inputs:
  kubernetes_cluster_name:
    description: Name of kubernetes cluster.
    required: true
  AWS_ACCESS_KEY_ID:
    description: Key used to access AWS.
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: Key used to access AWS secrets.
    required: true
  AWS_DEFAULT_REGION:
    description: Region you wish to use for AWS.
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        #!/usr/bin/env bash
        function get_kubernetes_config {
            aws eks update-kubeconfig --name ${KUBERNETES_CLUSTER_NAME} --region ${AWS_DEFAULT_REGION}
        }
      shell: bash
