name: "Build Persistent Variables From Vars File"
author: Evan Floyd <efloyd@idevops.io>
branding:
  icon: cloud
  color: gray-dark
description: Set Build Persistent Variables From Vars File
inputs:
  vars_file_location:
    description: Location of vars file to be used for setting persistent variables
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        import os
        import json
        vars_file=open(os.environ["VARS_FILE_LOCATION"], "r").read()
        json_var_object = json.loads(vars_file)
        append_github_file = open(os.environ["GITHUB_ENV"], "a")
        for key in json_var_object:
            value = json_var_object[key]
            key_value_string = key + "=" + value + "\n"
            append_github_file.write(key_value_string)
        append_github_file.close()
      shell: python
