name: "Anchore Docker Image Scan"
author: Kathryn Keep
branding:
  icon: cloud
  color: gray-dark
description: "Anchore Docker Image Scan"
inputs:
  docker_image_name:
    description: File you want to scan.
    required: true
runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2

  - name: "Anchore Docker Image Scan"
    run: |
        #!/usr/bin/env bash
        curl -s https://ci-tools.anchore.io/inline_scan-latest | bash -s -- -f ${{ github.event.inputs.docker_image_name }}
    shell: bash