name: "Anchore Grype Scan"
author: Kathryn Keep
branding:
  icon: cloud
  color: gray-dark
description: "Anchore Grype Scan"
inputs:
name: Container Image CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the container image
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest
      - uses: anchore/scan-action@v3
        with:
          image: "localbuild/testimage:latest"
          fail-build: true
name: Scan image
  uses: anchore/scan-action@v3
  with:
    image: "localbuild/testimage:latest"
    fail-build: true
    severity-cutoff: critical
runs:
  using: "composite"
  steps:
    - run: |
        #!/usr/bin/env bash
        curl -s https://ci-tools.anchore.io/inline_scan-latest | bash -s -- -f -d Dockerfile -b .anchore-policy.json example-image:latest
      shell: bash
