name: "Anchore Grype Scan"
author: Kathryn Keep
branding:
  icon: cloud
  color: gray-dark
description: "Anchore Grype Scan"
inputs:
  docker_image_name:
    description: path to docker image
    required: true
  fail_on_failure:
    description: --fail-on <severity>
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        #!/usr/bin/env bash
        curl -s https://ci-tools.anchore.io/inline_scan-latest | bash -s -- -f -d Dockerfile -b .anchore-policy.json example-image:latest
        ANCHORE_URL=${{ inputs.anchore_url }}
      shell: bash
