name: "K8S:APPLY:MANIFEST"
author: Evan Floyd <efloyd@idevops.io>
branding:
  icon: cloud
  color: gray-dark
description: Apply Kubernetes manifest file
inputs:
  manifest:
    description: Manifest file location you wish to use.
    required: true
  namespace:
    description: K8S Namespace.
    required: true
  kube_config_location:
    description: Location of the kubeconfig you want to use.
    default: "/home/runner/.kube/config"
    required: false
runs:
  using: "composite"
  steps:
    - run: |
        #!/usr/bin/env bash
        kubectl apply -f ${{ inputs.manifest }} -n ${{ inputs.namespace }} --kubeconfig=${{ inputs.kube_config_location }}
      shell: bash