name: "Anchore Docker Image Scan with Grype and Syft"
author: Jason Valest
branding:
  icon: cloud
  color: gray-dark
description: "Anchore Docker Image Scan with Grype and Syft"
inputs:
  docker_image_name:
    description: File you want to scan.
    required: true
  fail_pipeline_on_fail:
    description: Fail pipeline on scan.
    default: "true"
    required: true
runs:
  using: "composite"
  steps:
  - name: "Install Syft"
    run: |
        #!/usr/bin/env bash
        echo "Installing Syft..."
        echo ${{ inputs.docker_image_name }}
        if [ "${{ inputs.fail_pipeline_on_fail }}" == "true" ]; then
           sudo curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sudo sh -s -- -f -b ${{ inputs.docker_image_name }}
        else
          sudo curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sudo sh -s -- -b ${{ inputs.docker_image_name }}
        fi
    shell: bash

  - name: "Anchore Docker Image Scan"
    run: |
        #!/usr/bin/env bash
        echo ${{ inputs.docker_image_name }}
        if [ "${{ inputs.fail_pipeline_on_fail }}" == "true" ]; then
           sudo curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -f -b ${{ inputs.docker_image_name }}
        else
          sudo curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b ${{ inputs.docker_image_name }}
        fi
    shell: bash
timeout-minutes: 10
