name: "Use AWS CLI to pull K8S Kubeconfig"
author: Evan Floyd <efloyd@idevops.io>, Stephen Card <scard@idevops.io>
branding:
  icon: cloud
  color: gray-dark
description: Use AWS CLI to pull K8S Kubeconfig
inputs:
  kubernetes_cluster_name:
    description: Name of kubernetes cluster.
    required: true
  AWS_ACCESS_KEY_ID:
    description: Key used to access AWS.
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: Key used to access AWS secrets.
    required: true
  AWS_DEFAULT_REGION:
    description: Region you wish to use for AWS.
    required: true
runs:
  using: composite
  steps:
    - run: |
        #!/usr/bin/env bash
        export AWS_ACCESS_KEY_ID=$(echo ${{ inputs.AWS_ACCESS_KEY_ID }})
        export AWS_SECRET_ACCESS_KEY=$(echo ${{ inputs.AWS_SECRET_ACCESS_KEY }})
        export AWS_DEFAULT_REGION=$(echo ${{ inputs.AWS_DEFAULT_REGION }})
        #!/usr/bin/env bash
        curl -sSLO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        curl -sSo aws-iam-authenticator https://s3.us-west-2.amazonaws.com/amazon-eks/1.21.2/2021-07-05/bin/darwin/amd64/aws-iam-authenticator
        pip install awscli
        aws eks update-kubeconfig --name ${{ inputs.kubernetes_cluster_name }} --region ${{ inputs.AWS_DEFAULT_REGION }}
      shell: bash
