name: "Kubernetes validate deployment"
author: Evan Floyd <efloyd@idevops.io>, Stephen Card <scard@idevops.io>
branding:
  icon: cloud
  color: gray-dark
description: Kubernetes validate deployment
inputs:
  app_name:
    description: Name of the app you are deploying.
    required: true
  namespace:
    description: Kubernetes namespace you wish to use
    required: true
  aws_access_key_id:
    description: AWS Access Key.
    required: true
  aws_secret_access_key:
    description: AWS Secret Key.
    required: true
  aws_default_region:
    description: The default region for aws cli.
    required: true
  k8s_cluster_name:
    description: Name of the AWS cluster to deploy into.
    required: true

runs:
  using: "composite"
  steps:
  - run: |
      #!/usr/bin/env bash
      curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      curl -o aws-iam-authenticator https://s3.us-west-2.amazonaws.com/amazon-eks/1.21.2/2021-07-05/bin/darwin/amd64/aws-iam-authenticator
      pip install awscli
      cp kubectl /usr/bin/kubectl
      cp aws-iam-authenticator /usr/bin/aws-iam-authenticator
      chmod a+x /usr/bin/aws-iam-authenticator
      chmod a+x /usr/bin/kubectl
      aws eks update-kubeconfig --name ${INPUT_KUBERNETES_CLUSTER_NAME} --region ${INPUT_AWS_DEFAULT_REGION}
      kubectl rollout status deployment/${INPUT_APP_NAME} --namespace ${INPUT_NAMESPACE}
    shell: bash