name: "Docker Check, Build, Push"
author: Grant Zukel <admin@idevops.io>
branding:
  icon: cloud
  color: gray-dark
description: Create Route 53 Record Sets
inputs:
  docker_username:
    description: Docker Username in Docker Hub
    required: true
  docker_password:
    description: Docker Password for Docker Hub Authentication (PAT)
    required: true
  docker_org:
    description: The Docker Org your repo is in.
    required: true
  docker_image:
    description: The Docker image name.
    required: true
  docker_tag:
    description: The tag of the docker file you wish to set.
    required: true
  docker_file_location:
    description: Location of the docker file you are building.
    required: true
  docker_server_url:
    description: The url to push docker images to.
    default: "https://index.docker.io/v1/"
    required: false
runs:
  using: "composite"
  steps:
  -  run: |
      #!/usr/bin/env bash

      function build_and_push {
        docker build -t ${{ inputs.docker_org }}/${{ inputs.docker_image }}:${{ inputs.docker_tag }} ${{ inputs.docker_file_location }}
        docker push ${{ inputs.docker_org }}/${{ inputs.docker_image }}:${{ inputs.docker_tag }}
      }

      echo "Execute Docker Login"
      docker login ${{ inputs.docker_server_url }} --username "${{ inputs.docker_username }}" --password "${{ inputs.docker_password }}"

      echo "Try to pull image, if no pull build and push, if pull continue."
      docker pull ${{ inputs.docker_org }}/${{ inputs.docker_image }}:${{ inputs.docker_tag }} || build_and_push

     shell: bash
