name: "Apply Kubernetes manifest file"
author: Evan Floyd <efloyd@idevops.io>
branding:
  icon: cloud
  color: gray-dark
description: Apply Kubernetes manifest file
inputs:
  manifest:
    description: Manifest file location you wish to use.
    required: true
  namespace:
    description: K8S Namespace.
    required: true
  kubernetes_cluster_name:
    description: Name of the AWS cluster to deploy into.
    required: true
  AWS_ACCESS_KEY_ID:
    description: AWS Access Key.
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: AWS Secret Key.
    required: true
  AWS_DEFAULT_REGION:
    description: The default region for aws cli.
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        #!/usr/bin/env bash
        echo $INPUT_MANIFEST | base64 -d > deployment.yaml
        cat deployment.yaml
        export AWS_ACCESS_KEY_ID=$(echo $INPUT_AWS_ACCESS_KEY_ID)
        export AWS_SECRET_ACCESS_KEY=$(echo $INPUT_AWS_SECRET_ACCESS_KEY)
        export AWS_DEFAULT_REGION=$(echo $INPUT_AWS_DEFAULT_REGION)
        aws eks update-kubeconfig --name ${INPUT_K8S_CLUSTER_NAME} --region ${INPUT_AWS_DEFAULT_REGION}
        kubectl create namespace ${INPUT_NAMESPACE} || echo "Namespace Exists"
        kubectl apply -f deployment.yaml -n ${INPUT_NAMESPACE}
      shell: bash