name: "Apply Kubernetes manifest file"
author: Evan Floyd <efloyd@idevops.io>
branding:
  icon: cloud
  color: gray-dark
description: Apply Kubernetes manifest file
inputs:
  manifest:
    description: Manifest file location you wish to use.
    required: true
  namespace:
    description: K8S Namespace.
    required: true
  aws_access_key_id:
    description: AWS Access Key.
    required: true
  aws_secret_access_key:
    description: AWS Secret Key.
    required: true
  aws_default_region:
    description: The default region for aws cli.
    required: true
  k8s_cluster_name:
    description: Name of the AWS cluster to deploy into.
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        #!/usr/bin/env bash
        cat $MANIFEST
        echo  $MANIFEST | base64 -d > deployment.yaml
        cat deployment.yaml
        export AWS_ACCESS_KEY_ID=$(echo ${{ inputs.AWS_ACCESS_KEY_ID }})
        export AWS_SECRET_ACCESS_KEY=$(echo ${{ inputs.AWS_SECRET_ACCESS_KEY }})
        export AWS_DEFAULT_REGION=$(echo ${{ inputs.AWS_DEFAULT_REGION }})
        aws eks update-kubeconfig --name ${{ inputs.K8S_CLUSTER_NAME }} --region ${{ inputs.AWS_DEFAULT_REGION }}
        kubectl create namespace ${{ inputs.NAMESPACE }} || echo "Namespace Exists"
        kubectl apply -f deployment.yaml -n ${{ inputs.NAMESPACE }}
      shell: bash