name: "Create namespace & Docker Pull Secret"
author: Evan Floyd <efloyd@idevops.io>
branding:
  icon: cloud
  color: gray-dark
description: Create namespace & Docker Pull Secret
inputs:
  namespace:
    description: Namespace for kubernetes.
    required: true
  docker_host_url:
    description: Host url for Docker.
    required: true
  docker_username:
    description: Docker Username in Docker Hub.
    required: true
  docker_password:
    description: Docker Password for Docker Hub Authentication (PAT)
    required: true
  docker_pull_secret:
    description: Adds a secret to grant access for pods to pull images from registry.
    required: true
  kube_config_location:
    description: Location of the kubeconfig you want to use.
    default: "/home/runner/.kube/config"
    required: false
  aws_access_key_id:
    description: aws access key id
    default: ""
    required: false
  aws_access_secret_key:
    description: aws access secret key
    default: ""
    required: false
  aws_region:
    description: aws region you want to use
    default: "us-west-2"
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        #!/usr/bin/env bash
        export AWS_ACCESS_KEY_ID=${{ inputs.aws_access_key_id }}
        export AWS_SECRET_ACCESS_KEY=${{ inputs.aws_access_secret_key }}
        export AWS_DEFAULT_REGION=${{ inputs.aws_region }}

        kubectl create namespace ${{ inputs.namespace }} --kubeconfig=${{ inputs.kube_config_location }} || echo "Namespace Exists"

        kubectl create secret docker-registry ${{ inputs.docker_pull_secret }} \
        --docker-server="${{ inputs.docker_host_url }}" \
        --docker-username="${{ inputs.docker_username }}" \
        --docker-password="${{ inputs.docker_password }}" \
        --namespace ${{ inputs.namespace }} --kubeconfig=${{ inputs.kube_config_location }} || export EXISTS=yes

        if [ ! -z "${EXISTS}" ]; then
          kubectl delete secret ${{ inputs.docker_pull_secret }} -n ${{ inputs.namespace }} --kubeconfig=${{ inputs.kube_config_location }}
          kubectl create secret docker-registry ${{ inputs.docker_pull_secret }} \
          --docker-server="${{ inputs.docker_host_url }}" \
          --docker-username="${{ inputs.docker_username }}" \
          --docker-password="${{ inputs.docker_password }}" \
          --namespace ${{ inputs.namespace }} --kubeconfig=${{ inputs.kube_config_location }}
        fi

      shell: bash