name: "Create namespace & Docker Pull Secret"
author: Evan Floyd <efloyd@idevops.io>
branding:
  icon: cloud
  color: gray-dark
description: Create namespace & Docker Pull Secret
inputs:
  namespace:
    description: Namespace for kubernetes.
    required: true
  docker_host_url:
    description: Host url for Docker.
    required: true
  docker_username:
    description: Docker Username in Docker Hub.
    required: true
  docker_password:
    description: Docker Password for Docker Hub Authentication (PAT)
    required: true
  docker_pull_secret:
    description: Adds a secret to grant access for pods to pull images from registry.
    required: true
  kube_config_location:
    description: Location of the kubeconfig you want to use.
    default: "~/.kube/config"
    required: false
runs:
  using: "composite"
  steps:
    - run: |
        #!/usr/bin/env bash
        function kubernetes_create_namespace {
        NAMESPACE=$1
        kubectl create namespace ${1} --kubeconfig=${{ inputs.kube_config_location }} || echo "Namespace Exists"
        }

        function kubernetes_create_docker_secret {
        NAMESPACE=$1
        DOCKER_HOST_URL=$2
        DOCKER_USERNAME=$3
        DOCKER_PASSWORD=$4
        DOCKER_PULL_SECRET=$6
        EXISTS=

        kubectl create secret docker-registry ${INPUT_DOCKER_PULL_SECRET} \
        --docker-server="${INPUT_DOCKER_HOST_URL}" \
        --docker-username="${INPUT_DOCKER_USERNAME}" \
        --docker-password="${INPUT_DOCKER_PASSWORD}" \
        --namespace ${INPUT_NAMESPACE} --kubeconfig=${{ inputs.kube_config_location }} || export EXISTS=yes

        if [ ! -z ${EXISTS} ]; then
        kubectl delete secret ${INPUT_DOCKER_PULL_SECRET} -n ${INPUT_NAMESPACE} --kubeconfig=${{ inputs.kube_config_location }}
        kubectl create secret docker-registry ${INPUT_DOCKER_PULL_SECRET} \
        --docker-server="${INPUT_DOCKER_HOST_URL}" \
        --docker-username="${INPUT_DOCKER_USERNAME}" \
        --docker-password="${INPUT_DOCKER_PASSWORD}" \
        --namespace ${INPUT_NAMESPACE} --kubeconfig=${{ inputs.kube_config_location }}
        fi
        }
      shell: bash